name: Hardhat compile
on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      DEPLOYER_ADDRESS:           '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      PROXY_DEPLOYER_ADDRESS:     '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      PROXY_DEPLOYER_PRIVATE_KEY: 'aa283889a41899614de937816e8c9060cc2609f63de033db9f91828f414dd147'
      DEPLOYER_PRIVATE_KEY:       'aa283889a41899614de937816e8c9060cc2609f63de033db9f91828f414dd147'
      MESSENGER_0_ADDRESS:        '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      MESSENGER_1_ADDRESS:        '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      MESSENGER_2_ADDRESS:        '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      POOL_MESSENGER_0_ADDRESS:   '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      POOL_MESSENGER_1_ADDRESS:   '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      POOL_MESSENGER_2_ADDRESS:   '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      ARBISCAN_API_KEY:           ${{ secrets.ARBISCAN_API_KEY }}
      ETHERSCAN_API_KEY:          ${{ secrets.ETHERSCAN_API_KEY }}
      OPTIMISMSCAN_API_KEY:       ${{ secrets.OPTIMISMSCAN_API_KEY }}
      CELOSCAN_API_KEY:           ${{ secrets.CELOSCAN_API_KEY }}
      BASESCAN_API_KEY:           ${{ secrets.BASESCAN_API_KEY }}
      POLYGONSCAN_API_KEY:        ${{ secrets.POLYGONSCAN_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          cd packages/hardhat
          yarn install
      - name: Compile Hardhat project
        run: |
          cd packages/hardhat
          yarn hardhat compile
