name: Hardhat compile
on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      DEPLOYER_ADDRESS:           '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      PROXY_DEPLOYER_ADDRESS:     '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      PROXY_DEPLOYER_PRIVATE_KEY: '000000000000000000000000000000000000000000'
      DEPLOYER_PRIVATE_KEY:       '000000000000000000000000000000000000000000'
      MESSENGER_0_ADDRESS:        '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      MESSENGER_1_ADDRESS:        '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      MESSENGER_2_ADDRESS:        '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      POOL_MESSENGER_0_ADDRESS:   '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      POOL_MESSENGER_1_ADDRESS:   '0xdddd5f804b9d293dce8819d232e8d76381605a62'
      POOL_MESSENGER_2_ADDRESS:   '0xdddd5f804b9d293dce8819d232e8d76381605a62'
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          cd packages/hardhat
          yarn install
      - name: Compile Hardhat project
        run: |
          cd packages/hardhat
          yarn hardhat compile
