name: Hardhat compile
on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          cd packages/hardhat
          npm install -g bun
          bun install
      - name: Compile Hardhat project
        run: |
          cd packages/hardhat
          bun hardhat compile
